# Generated by Django 2.0.6 on 2018-06-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empregador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='nao informado', max_length=50)),
                ('email', models.CharField(default='nao informado', max_length=30)),
                ('idGmail', models.CharField(default='nao informado', max_length=30)),
                ('requisitos', models.CharField(default='nao informado', max_length=500)),
                ('formacao', models.CharField(default='nao informado', max_length=500)),
                ('experiencia', models.CharField(default='nao informado', max_length=500)),
                ('salario', models.CharField(default='nao informado', max_length=20)),
                ('local', models.CharField(default='nao informado', max_length=50)),
                ('disponibilidade', models.CharField(default='nao informado', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Trabalhador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='nao informado', max_length=50)),
                ('nascimento', models.CharField(default='nao informado', max_length=15)),
                ('cpf', models.CharField(default='nao informado', max_length=20)),
                ('email', models.CharField(default='nao informado', max_length=30)),
                ('nacionalidade', models.CharField(default='nao informado', max_length=30)),
                ('estadoCivil', models.CharField(default='nao informado', max_length=15)),
                ('endereco', models.CharField(default='nao informado', max_length=100)),
                ('cidade', models.CharField(default='nao informado', max_length=20)),
                ('unidadeFederal', models.CharField(default='nao informado', max_length=15)),
                ('telefone', models.CharField(default='nao informado', max_length=15)),
                ('celular', models.CharField(default='nao informado', max_length=15)),
                ('infoPessoal', models.CharField(default='nao informado', max_length=100)),
                ('idGmail', models.CharField(default='nao informado', max_length=30)),
                ('objetivo', models.CharField(default='nao informado', max_length=100)),
                ('perfil', models.CharField(default='nao informado', max_length=100)),
                ('experiencia', models.CharField(default='nao informado', max_length=100)),
                ('formacao', models.CharField(default='nao informado', max_length=100)),
                ('cursoComplementar', models.CharField(default='nao informado', max_length=100)),
                ('idiomas', models.CharField(default='nao informado', max_length=100)),
                ('infoProfissional', models.CharField(default='nao informado', max_length=100)),
            ],
        ),
    ]
