# Generated by Django 2.0.5 on 2018-07-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregador',
            name='disponibilidade',
            field=models.TextField(blank=True, default='Não Informado!', null=True),
        ),
        migrations.AlterField(
            model_name='empregador',
            name='email',
            field=models.TextField(blank=True, default='Não Informado!', null=True),
        ),
        migrations.AlterField(
            model_name='empregador',
            name='experiencia',
            field=models.TextField(blank=True, default='Não Informado!', null=True),
        ),
        migrations.AlterField(
            model_name='empregador',
            name='formacao',
            field=models.TextField(blank=True, default='Não Informado!', null=True),
        ),
        migrations.AlterField(
            model_name='empregador',
            name='idGmail',
            field=models.TextField(blank=True, default='Não Informado!', null=True),
        ),
        migrations.AlterField(
            model_name='empregador',
            name='local',
            field=models.TextField(blank=True, default='Não Informado!', null=True),
        ),
        migrations.AlterField(
            model_name='empregador',
            name='nome',
            field=models.TextField(blank=True, default='Não Informado!', null=True),
        ),
        migrations.AlterField(
            model_name='empregador',
            name='requisitos',
            field=models.TextField(blank=True, default='Não Informado!', null=True),
        ),
        migrations.AlterField(
            model_name='empregador',
            name='salario',
            field=models.TextField(blank=True, default='Não Informado!', null=True),
        ),
    ]
